### ISSUE TITLE
wayland(sway)下截屏报错

### ISSUE THREAD

**Issue by 383494** [xushengfeng/eSearch#127]
**描述问题**
报错：
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: buffer must be a node Buffer
  at /usr/lib/e-search/app/out/main/main.js:4656:38
  at Array.forEach(<anonymous>)
  at quick_clip (/usr/lib/e-search/app/out/main/main.js:4655:29)
  at arg_run (/usr/lib/e-search/app/out/main/main.js:3313:7)
  at App.<anonymous> (/usr/lib/e-search/app/out/main/main,js:3290:5)
  at App.emit(node:events:527:28)
```
**重现步骤**

1. 在任意界面
2. 点击截屏快捷键或用`e-search -q`
3. 发生错误

**本应该**
显示截屏内容

**屏幕截图**

**设备和软件信息**

-   操作系统和具体版本:Arch Linux
-   屏幕参数:1920x1080
-   软件版本:AUR e-search 1.9.8-1

**更多信息**

**Comment by xushengfeng** [comment]
![eSearch-2023-03-28-19-37-38](https://user-images.githubusercontent.com/28475549/228224497-42e62fa9-e287-4c7f-bcab-f677e549988f.png)
由于wayland的限制，截屏时系统会弹出共享请求框，取消后会无法读取截屏，从而报错
